name: Deploy Python App to Oracle VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy project to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "."
          target: "~/ticket-watcher"

      - name: SSH and run app
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ~/ticket-watcher
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pm2 delete ticket-watcher || true

            echo "CHAT_ID=${{ secrets.CHAT_ID }}" > .env
            echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env

            pm2 start venv/bin/python --name ticket-watcher -- -u bot.py
            pm2 save
            exit 0
